# https://github.com/evrmji/blog/.travis.yml
sudo: disable
language: node_js
node_js:
  - 12
cache:
  npm: true
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli
  - hexo init $HOME/generate
  - wget https://github.com/jgm/pandoc/releases/download/2.9.2/pandoc-2.9.2-1-amd64.deb
  - sudo dpkg -i pandoc-2.9.2-1-amd64.deb
install:
  # Copy posts
  - rm $HOME/generate/source/_posts/* -rf
  - find $TRAVIS_BUILD_DIR/20*/ -name "*.md" | xargs -i cp -r {} $HOME/generate/source/_posts/
  - find $TRAVIS_BUILD_DIR/source/ -name "*.md" | xargs -i cp -r {} $HOME/generate/source/
  # Init theme
  - git clone https://github.com/SukkaW/hexo-theme-suka $HOME/generate/themes/suka
  - cd $HOME/generate/themes/suka
  - npm install --production
  # Add support of Tex
  - npm uninstall hexo-renderer-marked --save
  - npm install hexo-renderer-pandoc --save
  # Copy config files
  - cp $TRAVIS_BUILD_DIR/_site_config.yml $HOME/generate/_config.yml
  - cp $TRAVIS_BUILD_DIR/_theme_config.yml $HOME/generate/themes/suka/_config.yml
script:
  - cd $HOME/generate
  - hexo generate
  # Copy other files
  - cp -r $TRAVIS_BUILD_DIR/source/img/ $HOME/generate/public/
  - cp -r $TRAVIS_BUILD_DIR/source/files/ $HOME/generate/public/
  - cp -r $TRAVIS_BUILD_DIR/source/CNAME $HOME/generate/public/CNAME

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: $HOME/generate/public
  target_branch: gh-pages
  
branches:
  only:
    - master
