sudo: disable
language: node_js
node_js:
  - 12 # use nodejs v12 LTS
cache:
  directories:
    - node_modules

before_install:
  - npm install -g hexo-cli
  - mkdir $HOME/generate
  - cd $HOME/generate
  - hexo init
install:
  - cp $TRAVIS_BUILD_DIR/archive*/ $HOME/generate/source -r

  - git clone https://github.com/SukkaW/hexo-theme-suka $HOME/generate/themes/suka
  - cd $HOME/generate/themes/suka
  - npm install --production

  - cp $TRAVIS_BUILD_DIR/_site_config.yml $HOME/generate/_config.yml
  - cp $TRAVIS_BUILD_DIR/_theme_config.yml $HOME/generate/themes/_config.yml
script:
  - cd $HOME/generate
  - hexo generate

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: $HOME/generate/public
  target_branch: gh-pages
  
branches:
  only:
    - master
