sudo: disable
language: node_js
node_js:
  - 12
cache:
  npm: true
  directories:
    - node_modules

before_install:
  - node -v
  - npm -v
  - npm install -g hexo-cli
  - hexo init $HOME/generate
  - hexo -v
install:
  - rm $HOME/generate/source/_posts/* -rf
  - find $TRAVIS_BUILD_DIR/*/ -name "*.md" | xargs -i cp -r {} $HOME/generate/source/_posts/

  - git clone https://github.com/SukkaW/hexo-theme-suka $HOME/generate/themes/suka
  - cd $HOME/generate/themes/suka
  - npm install --production
  - npm ls --depth 0

  - cp $TRAVIS_BUILD_DIR/_site_config.yml $HOME/generate/_config.yml
  - cp $TRAVIS_BUILD_DIR/_theme_config.yml $HOME/generate/themes/_config.yml
script:
  - cd $HOME/generate
  - hexo generate --debug

deploy:
  provider: pages
  cleanup: false
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
  local_dir: $HOME/generate/public
  target_branch: gh-pages
  
branches:
  only:
    - master
