sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
install:
  - npm install -g hexo-cli
branches:
  only:
    - master # build master branch only
script:
  - hexo init # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: gh-pages
  local-dir: /
