# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

# Website
title: blog
keywords: 计算机科学, 算法
description: 记录点东西
timezone: Asia/Shanghai

# URL
url: evrmji.org
permalink: :year/:title/


theme: suka
# Suka Theme config
# Documents: https://theme-suka.skk.moe/docs/
suka_theme:
  search:
    enable: true
    path: search.json
    field: all # Page | Post | All. Default post
  prism:
    enable: true
    line_number: true
    theme: default