# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

# Website
title: aero
keywords: 计算机科学, 算法
description: 记录点东西
author: aero(evrmji)
language: zh-CN
timezone: Asia/Shanghai

# URL
url: https://evrmji.org
root: /
permalink: :year/:title/


theme: suka
# Suka Theme config
# Documents: https://theme-suka.skk.moe/docs/
suka_theme:
  search:
    enable: true
    path: search.json
    field: all # Page | Post | All. Default post
  prism:
    enable: true
    line_number: true
    theme: default

math:
  engine: 'katex' # or 'mathjax'
  # MathJax config
  mathjax:
    src: https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js

  # KaTeX config
  katex:
    css: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.css
    js: https://cdnjs.cloudflare.com/ajax/libs/KaTeX/0.6.0/katex.min.js # not used
